// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiksGZW4KGGHdxOUMTRhcFcv6R-EUMYg8',
    appId: '1:321276071122:web:7944027c77e88135f6f10b',
    messagingSenderId: '321276071122',
    projectId: 'skillswapper-7b66d',
    authDomain: 'skillswapper-7b66d.firebaseapp.com',
    storageBucket: 'skillswapper-7b66d.firebasestorage.app',
    measurementId: 'G-2MT6XVKDMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGK46QdvK1d_JByLaDbq7ORIepEXphKM',
    appId: '1:321276071122:android:386f4430606e7c84f6f10b',
    messagingSenderId: '321276071122',
    projectId: 'skillswapper-7b66d',
    storageBucket: 'skillswapper-7b66d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq6zdar1j0N84Yo4mAVlp5q90WNFz3MH4',
    appId: '1:321276071122:ios:3ea3be137cf5df45f6f10b',
    messagingSenderId: '321276071122',
    projectId: 'skillswapper-7b66d',
    storageBucket: 'skillswapper-7b66d.firebasestorage.app',
    iosBundleId: 'com.example.skillswapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq6zdar1j0N84Yo4mAVlp5q90WNFz3MH4',
    appId: '1:321276071122:ios:3ea3be137cf5df45f6f10b',
    messagingSenderId: '321276071122',
    projectId: 'skillswapper-7b66d',
    storageBucket: 'skillswapper-7b66d.firebasestorage.app',
    iosBundleId: 'com.example.skillswapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiksGZW4KGGHdxOUMTRhcFcv6R-EUMYg8',
    appId: '1:321276071122:web:cbf29991ca063f35f6f10b',
    messagingSenderId: '321276071122',
    projectId: 'skillswapper-7b66d',
    authDomain: 'skillswapper-7b66d.firebaseapp.com',
    storageBucket: 'skillswapper-7b66d.firebasestorage.app',
    measurementId: 'G-LXHKDBYZW3',
  );
}
